apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trading-alerts

resources:
  - service.yaml
  - statefulset.yaml

configMapGenerator:
  - name: postgres-init
    files:
      - init.sql  # use external sql file instead of inline sql for better editablility and version control

generatorOptions:
  disableNameSuffixHash: true