apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: trading-alerts
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: trading-worker:dev
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trading-alerts-secrets
                  key: redis-password
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trading-alerts-secrets
                  key: postgres-password
