apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - apps/app-config.yaml
  - apps/trading-alerts-sealedsecret.yaml
  
  - apps/api
  - apps/fetcher
  - apps/postgres
  - apps/redis
  - apps/worker
  
  - security/network-policies.yaml